version: "3.8"

services:
  # Cơ Sở Dữ Liệu PostgreSQL Container
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-appchat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-appchat}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appchat"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache Container
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    environment:
      # Ghi đè lại URL để trỏ vào IP nội bộ của container DB và Redis vừa tạo
      - DATABASE_URL=postgres://${POSTGRES_USER:-appchat}:${POSTGRES_PASSWORD:-secretpassword}@db:5432/${POSTGRES_DB:-appchat}
      - REDIS_URL=redis://redis:6379
      - IP=0.0.0.0 # Bắt buộc phải là 0.0.0.0 để expose port ra ngoài host!!
    extra_hosts:
      - "host.docker.internal:host-gateway" # Cú pháp mapping host trên Linux

    restart: unless-stopped
    volumes:
      # Map để lưu file cục bộ nếu không up lên Cloudinary
      - ./uploads:/app/uploads

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
